### ISSUE TITLE
Missing entries

### ISSUE THREAD

**Issue by ghost** [JackCuthbert/pihole-twitter#1]
```
$ host twitter.co.uk 8.8.8.8
Using domain server:
Name: 8.8.8.8
Address: 8.8.8.8#53
Aliases: 

twitter.co.uk has address 216.146.46.10
twitter.co.uk has address 216.146.46.11
```
Twtr has DNS for every country not just the UK.

**Comment by JackCuthbert** [comment]
Thanks! I'll add these ones and a couple that I can think of. For the other countries I'll happily add them on request or from PRs.
