### ISSUE TITLE
Q: Does this list block all Twitter content or just inline Ads served via Twitter?

### ISSUE THREAD

**Issue by quadcom** [JackCuthbert/pihole-twitter#4]
I made the assumption that this list would block the ADs on Twitter, but it seems to kill all content completely.

What is it they say about assuming?

**Comment by JackCuthbert** [comment]
This will completely block Twitter 🙂

If you'd like to submit a PR or respond with domains that serve ads from Twitter I'd happily create a new list in this repo for it. I try to keep my lists up to date.

Edit: I'll add a note in the readme explaining that it blocks Twitter completely too.
